# Generated by Django 3.2.9 on 2021-12-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vprasanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vprasanje', models.CharField(max_length=1000)),
                ('pravilen_odgovor', models.CharField(max_length=1000)),
                ('napacen_odgovor_1', models.CharField(max_length=1000)),
                ('napacen_odgovor_2', models.CharField(max_length=1000)),
                ('namig', models.CharField(max_length=1000)),
                ('slika', models.CharField(max_length=1000)),
                ('level', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pravilen', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zgodovinakviz.vprasanje')),
            ],
        ),
    ]
