# Generated by Django 3.2.9 on 2021-12-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zgodovinakviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=1000)),
                ('vrstni_red', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='odgovor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odgovor',
            name='vprasanje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.vprasanje'),
        ),
        migrations.AlterField(
            model_name='vprasanje',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vprasanje',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.level'),
        ),
    ]
