# Generated by Django 3.2.9 on 2021-12-08 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zgodovinakviz', '0002_auto_20211208_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrikazanaVprasanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zgodovinakviz.uporabnik')),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zgodovinakviz.vprasanje')),
            ],
        ),
        migrations.AlterField(
            model_name='odgovor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.uporabnik'),
        ),
        migrations.AlterField(
            model_name='vprasanje',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.uporabnik'),
        ),
    ]
