# Generated by Django 3.2.9 on 2021-12-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgodovinakviz', '0004_remove_vprasanje_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='odgovor',
            name='izbran_odgovor',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
