# Generated by Django 3.2.9 on 2022-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgodovinakviz', '0005_odgovor_izbran_odgovor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vprasanje',
            name='slika',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
