# Generated by Django 3.2.9 on 2022-01-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgodovinakviz', '0006_alter_vprasanje_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='vprasanje',
            name='slika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgodovinakviz.slika'),
        ),
    ]
