# Generated by Django 3.2.9 on 2022-01-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgodovinakviz', '0007_auto_20220102_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='uporabnik',
            name='ucitelj',
            field=models.BooleanField(default=False),
        ),
    ]
