# Generated by Django 3.2.9 on 2022-01-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgodovinakviz', '0009_vprasanje_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='uporabnik',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
